name: quoscient
description: "A new Flutter project."
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  confetti: ^0.8.0
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.3
  flutter_riverpod: ^3.0.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.2.2
  skeletonizer: ^2.1.0+1
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  go_router_builder: ^4.0.1
  json_serializable: ^6.8.0
  lint: ^2.3.0
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

dependency_overrides:
  analyzer_plugin: 0.13.10

flutter:
  uses-material-design: true
